<?php
// $Id: feeds_defaults.module,v 1.3 2010/02/28 17:16:25 alexb Exp $

/**
 * @file
 * Default importer configurations for Feeds module.
 */

require_once(dirname(__FILE__) .'/feeds_defaults.features.inc');

/**
 * Implementation of hook_node_info().
 */
function feeds_defaults_node_info() {
  $items = array();
  if (in_array('feed', feeds_enabled_importers())) {
    $items['feed'] = array(
      'name' => t('Feed'),
      'module' => 'node',
      'description' => t('Subscribe to RSS or Atom feeds. Creates nodes of the content type "Feed item" from feed content.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'has_body' => '1',
      'body_label' => t('Body'),
      'locked' => TRUE,
    );
    $items['feed_item'] = array(
      'name' => t('Feed item'),
      'module' => 'node',
      'description' => t('This content type is being used for automatically aggregated content from feeds.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'has_body' => '1',
      'body_label' => t('Body'),
      'locked' => TRUE,
    );
  }
  if (in_array('feed_fast', feeds_enabled_importers())) {
    $items['feed_fast'] = array(
      'name' => t('Fast feed'),
      'module' => 'node',
      'description' => t('Subscribe to RSS or Atom feeds. Create light weight database records from feed content.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'has_body' => '1',
      'body_label' => t('Body'),
      'locked' => TRUE,
    );
  }
  return $items;
}
