<?php

include_once('wn_takeaction.features.inc');

/**
 * Implementation of hook_views_pre_render(&$view).
 * Add a link at the top of the "Take Action" page view to allow for views sorting.
 */
function wn_takeaction_views_pre_render(&$view) {
  if (($view->name == 'take_action') && ($view->current_display == 'page_1') && (user_access('Allow Reordering'))) {
    $view->attachment_before .= '<div class="draggable"><a href="/take_action/draggable">[Sort campaigns]</a></div>';
  }
}
