<?php
function wn_components_profiler_components_alter( &$components ) {
  $components['follow'] = array('callback' => 'wn_components_install_follow_links');
}

function wn_components_install_follow_links($follow_links, $config, &$identifiers) {
  foreach($follow_links as $uid => $links ) {
    $weight = 0;
    foreach($links as $name => $link ) {
      $follow_link = array(
        'uid'  => $uid,
        'path' => $url,
        'name' => $name,
        'weight' => $weight++
      );
      follow_link_save( (object) $follow_link );
    }
  }
}
