<?php

include_once('wn_common.features.inc');

/**
 * Implementation of hook_block().
 */
function wn_common_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {

    case 'list':
      // Placing any sidebar content created at the node level into a sidebar.
      $blocks[0]['info'] = t('Sidebar content');
      return $blocks;

      case 'view':
        if ($delta == 0) { // Build the sidebar block.
          $node = node_load(arg(1)); // If not empty, grab the sidebar content from the current node.
          $sidebar = $node->field_sidebar[0]['value'];
          $sidebar = rtrim($sidebar); // Sometimes the WYSIWYG editor adds whitespace to the end of a post.
          if ( !(empty($sidebar)) && ($sidebar != "<br />") ) {
            $block['subject'] = t('');
            $block['content'] = $sidebar;
            return $block;
          } else { break; }
        }

      return $block;
  }    
}

