<?php

include_once('wn_events.features.inc');

/**
 * Implementation of hook_block().
 * 
 * Provides a customizable block that pulls a view of events, with a configurable title and # of posts.
 */
function wn_events_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {

    case 'list':
      $blocks[0]['info'] = t('Events - Customizable listing');
      return $blocks;

    case 'configure':
      if ($delta == 0 && user_access('administer site configuration')) {
        $form['wn_events_number'] = array(
          '#type' => 'select',
          '#title' => t('Number of event posts shown on the homepage'),
          '#default_value' => variable_get('wn_events_number','3'),
          '#options' => array('0', '1', '2', '3', '4', '5'),
          '#description' =>t('Enter the maximum number of events to post on the homepage. If zero, this block will not display.'),
          );
      }
      return $form;

    case 'save':
      if ($delta == 0) {
        variable_set('wn_events_number', $edit['wn_events_number']);
      }
      break;

    case 'view':
      if ($delta == 0) {
        if (variable_get('wn_events_number', '3') != '0') { // If count set to zero, do no display block.
          $block['content'] = _wn_events_homepage_list();
        } 
      }

      return $block;
  }    
}

/**
 * Helper function for displaying homepage events listing.
 * Generates our vendered view of events.
 */
function _wn_events_homepage_list() {
  $view = views_get_view('events'); // Great the events view.
  $view->set_display('block_1'); // Set the display.
  $view->set_items_per_page(variable_get('wn_events_number', '3')); // Look up the number of events to display. 
  $output = $view->render($view_display); // Output the view.
  return $output;
}