<?php

include_once('wn_blog.features.inc');

/**
 * Implementation of hook_block().
 * 
 * Provides a customizable block that pulls a view of blog posts, with a configurable title and # of posts.
 */
function wn_blog_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {

    case 'list':
      $blocks[0]['info'] = t('Updates - Customizable listing');
      return $blocks;

    case 'configure':
      if ($delta == 0) {
        // @FIXME - Note: B/c of a narly bug in core. Have to use our own block title field to work across
        // all themes, when using an admin theme. See: http://drupal.org/node/374501.
        $form['wn_blog_title'] = array(
          '#type' => 'textfield',
          '#title' => t('Update block title'),
          '#default_value' => variable_get('wn_blog_title','Recent updates'),
          '#description' =>t('Enter a custom title for this updates homepage block.'),
          );
        $form['wn_blog_number'] = array(
          '#type' => 'select',
          '#title' => t('Number of event posts shown on the homepage'),
          '#default_value' => variable_get('wn_blog_number','3'),
          '#options' => array('0', '1', '2', '3', '4', '5'),
          '#description' =>t('Enter the maximum number of blog posts to post on the homepage. If zero, this block will not display.'),
          );
      }
      return $form;

    case 'save':
      if ($delta == 0) {
        variable_set('wn_blog_title', $edit['wn_blog_title']);
        variable_set('wn_blog_number', $edit['wn_blog_number']);
      }
      break;

    case 'view':
      if ($delta == 0) {
        if (variable_get('wn_blog_number', '3') != '0') { // If count set to zero, do no display block.
          $block['subject'] = t(variable_get('wn_blog_title', 'Recent updates'));
          $block['content'] = _wn_blog_homepage_list();
        } 
      }

      return $block;
  }    
}

/**
 * Helper function for displaying homepage blog listing.
 * Generates our vendered view of blog posts.
 */
function _wn_blog_homepage_list() {
  $view = views_get_view('updates'); // Great the blog view.
  $view->set_display('block_1'); // Set the display.
  $view->set_items_per_page(variable_get('wn_blog_number', '3')); // Look up the number of blog posts to display.   
  $output = $view->render($view_display);
  if (!empty($view->result)) { // If view returns results, output the view. We call after render so that view runs.
    return $output;
  }
}

/**
 * (Snippet taken from Managing News.)
 *
 * Implementation of hook_form_alter().
 *
 * The hook_form_[form_id]_alter() syntax is not used here as it will
 * get called prior to Feeds.
 */
function wn_blog_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'update_feed_node_form') {
    // Unset the URL field title.
    unset($form['feeds']['FeedsHTTPFetcher']['source']['#title']);
    // Make the description more specific.
    $form['feeds']['FeedsHTTPFetcher']['source']['#description'] = t('Enter a URL to a valid RSS or Atom feed.');
    // Instead, give its fieldset a nice title.
    $form['feeds']['#title'] = t('Feed URL');
    $form['feeds']['#title'] .= "\n<span class='form-required'>*</span>";
    // Move it all the way up top.
    $form['feeds']['#weight'] = -10;

    // Hide the node's title field in a fieldset. This will expand if the title
    // can't be populated from feed.
    $title = $form['title'];
    unset($title['#title']);
    $form['title'] = array(
      '#type' => 'fieldset',
      '#title' => t('Optional feed title'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['title']['title'] = $title;
  }
  // See explanation in wn_blog_block(). We have to use our own block title here.
  if (($form_id == 'block_admin_configure') && ($form['module']['#value'] == 'wn_blog')) {
    unset($form['block_settings']['title']);
  }
}

/**
 * Rewrite the search query to exclude selected node types.
 *
 * @see http://www.lullabot.com/articles/hiding-content-drupals-search-system
 * @see http://drupal.org/node/111744 if you want to help get something
 * sensible into core.
 */
function wn_blog_db_rewrite_sql($query, $primary_table, $primary_field, $args) {
  if ($query == '' && $primary_table == 'n' && $primary_field = 'nid' && empty($args)) {
    $excluded_types = array(
      'update_feed',
    );
    if (!empty($excluded_types)) {
      $where = " n.type NOT IN ('". join("','", $excluded_types) ."') ";
      return array('where' => $where);
    }
  }
}
