<?php
include_once('wn_hp_callout.features.inc');

/* hide wn_hp_callout content type from search */
function wn_hp_callout_db_rewrite_sql($query, $primary_table, $primary_field, $args) {
  if ($query == '' && $primary_table == 'n' && $primary_field = 'nid' && empty($args)) {
    $excluded_types = array('wn_hp_callout');
    if (!empty($excluded_types)) {
      $where = " n.type NOT IN ('". join("','", $excluded_types) ."') ";
      return array('where' => $where);
    }
  }
}

/**
 * Implementation of hook_form_FORMID_alter().
 *
 * Add the option of switching homepage callout slideshow formats.
 */
function wn_hp_callout_form_system_site_information_settings_alter(&$form, $form_state) {
  $form['hp_slideshow'] = array(
     '#type' => 'radios',
     '#title' => t('Homepage slideshow'),
     '#options' => array('full' => 'Full-width image', 'half' => 'With textbox'),
     '#default_value' => variable_get('hp_slideshow', 'full'),
     '#description' => t('Which of the two slideshow options would like you like for your homepage?'),
   );
}

/**
 * Implementation of Hook_nodeapi().
 * Used to add CSS and javascript when viewing a callout node.
 */
function wn_hp_callout_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

  if( $node->type == 'wn_hp_callout' && $op == 'view') {

    // Load Module's css and javascript.
    drupal_add_css((drupal_get_path('module', 'wn_hp_callout')) . '/css/wn_hp_callout.css');
    drupal_add_js((drupal_get_path('module', 'wn_hp_callout')) . '/js/jquery.cycle.min.js');
    drupal_add_js((drupal_get_path('module', 'wn_hp_callout')) . '/js/wn_hp_callout.js');

    $imgs = array();
    foreach( $node->field_wn_hp_callout_image as $img_data ) {
      $title = '<div class="wn-hp-callout-title">' . check_plain($img_data['data']['title']) .'</div>';

      $desc = $img_data['data']['wn_hp_callout_desc'];
      $desc = '<div class="wn-hp-callout-content">' . check_markup($desc['body'], $desc['format'], FALSE).'</div>';

      $img = theme('imagecache', 'wn_hp_callout', $img_data['filepath'], $img_data['data']['alt'], $img_data['data']['title']);

      $imgs[] = $img . '<div class="wn-hp-callout-entry">' . $title . $desc . '</div>';
    }
    $list = theme('item_list',$imgs, NULL, $type = 'ul');
    $list = str_replace('class="item-list"','',$list);
    $html = '<div class="wn-hp-callout">'.$list.'</div>';

    $node->content = array(
      'body' => array(
        '#value' => $html
      )
    );
  }
}