<?php

/**
 * @file
 * This file holds the functions for the installing
 * and enabling of the openlayers_ui module.
 *
 * @ingroup openlayers
 */

/**
 * Implementation of hook_uninstall().
 */
function openlayers_ui_uninstall() {
  // Get module variables
  $results = db_query("SELECT v.name FROM {variable} AS v WHERE v.name LIKE '%s%%'", 'openlayers_ui_');
  // Remove variables
  while ($row = db_fetch_array($results)) {
    variable_del($row['name']);
  }
}
