<?php

/**
 * Implmentation of hook_init().
 */
function wn_helper_init() {
  // Load wn_helper's css and javascript.
  drupal_add_css((drupal_get_path('module', 'wn_helper')) . '/css/wn_helper.css');
  drupal_add_js((drupal_get_path('module', 'wn_helper')) . '/js/wn_helper.js');
}


/**
 * Implementation of hook_theme().
 */
function wn_helper_theme() {
  $items = array();

  $items['wn_helper_follow_link'] = array(
    'arguments' => array('link' => NULL, 'title' => NULL),
  );

  return $items;
}

function wn_helper_theme_registry_alter(&$theme_registry) {
  $theme_registry['follow_link']['function'] = 'wn_helper_follow_link';
}

/**
 * Implementation of hook_help().
 *
 * Adds a help message our our custom dashboard.
 */
function wn_helper_help($path, $arg) {
  switch ($path) {
    case 'admin/dashboard':
      return 'Welcome to the Watershed Now! Dashboard. Here you will find quick links and other tools for managing your site. If you get stuck, consider reaching out to the maintainers of Watershed Now!, <a href="http://thinkshout.com/contact" target="_blank">ThinkShout.com</a>.';
  }
}

/**
 * Implementation of hook_menu().
 *
 * Adds a customized dashboard menu item and page.
 */
function wn_helper_menu() {
  $items = array();

  $items['admin/dashboard'] = array(
    'title' => 'Watershed Now! Dashboard',
    'page callback' => 'wn_helper_dashboard',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'wn_helper.admin.inc',
    'weight' => -20,
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 *
 * Borrowing heavily from Development Seed.
 */
function wn_helper_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'system_site_information_settings':
    // Allow for custom page title on site front page
      $form['site_name']['#title'] = 'Website Name';
      $form['site_name']['#description'] = 'The name of this website - Generally recommended to be your organization\'s name.';
      $form['site_slogan']['#access'] = FALSE;
      $form['site_mission']['#access'] = FALSE;
      $form['site_footer']['#access'] = FALSE;
      $form['anonymous']['#access'] = FALSE;
      break;
    case 'system_themes_form':
    // Hide cruddy themes that we don't want folks to use, as well as admin themes that are fixed.
      $hidden_themes = array('bluemarine', 'chameleon', 'garland', 'minnelli', 'marvin', 'pushbutton', 'cube', 'rubik', 'tao');
      foreach ($hidden_themes as $theme) {
        unset($form[$theme]);
        unset($form['status']['#options'][$theme]);
        unset($form['theme_default']['#options'][$theme]);
      }
      break;
  }
}


function wn_helper_follow_link($link, $title) {
  return theme('wn_helper_follow_link',$link,$title);
}

/**
 * Theme function to print an individual link.
 *
 * @param $link
 *   A follow link object.
 * @param $title
 *   The translated title of the social network.
 */
function theme_wn_helper_follow_link($link, $title) {
  $classes = array();
  $classes[] = 'follow-link';
  $classes[] = "follow-link-{$link->name}";
  $classes[] = $link->uid ? 'follow-link-user' : 'follow-link-site';
  $attributes = drupal_attributes(array(
    'class' => implode(' ', $classes),
    'href' => $link->url,
    'title' => follow_link_title($link->uid) .' '. $title,
    'rel' => 'me external',
    'target' => '_blank'
  ));

  return "<a$attributes>$title</a>\n";
}