<?php

include_once('wn_map.features.inc');

/**
 * Implementation of hook_views_pre_render().
 * Main map uses taxonomy-based map icons. B/c we can't guarantee that icons
 * exist for every taxonomy term, we check to see if an icon file exists, and if not,
 * we change the icon path in the view.
 */
function wn_map_views_pre_render(&$view) {
  if (($view->name == 'map_feature_data') || ($view->name == 'map_feature_data_with_args')) {
    
    foreach ($view->result as $row) { // Iterate through results.
      $tid = $row->term_data_tid; // Get term ID.
      $img_url = taxonomy_image_get_url($tid); // Look up term's image URL.
      $default_img = drupal_get_path('module', 'wn_map') . '/openlayers_themes/wn/icons/poi.png';
      if (!empty($img_url)) {
        $row->term_data_tid = $img_url; // If term image exists, use it.
      } else {
        $row->term_data_tid = $default_img; // Else use default image.
      }
    }
  }
}

/**
 * Implementation of Hook_form_alter().
 * Limiting taxonomy image form display to taxonomy terms of the Map point vocabulary.
 * @TODO - Make this configurable. Pry not worth it until upgrading to D7 and reworking with fields.module
 */
function wn_map_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'taxonomy_form_term':
    if (!in_array('map_feature', $form['#vocabulary']['nodes'])) {
      unset($form['taxonomy_image']);
    }
    break;
  }
}