<?php

include_once('wn_map.features.inc');

/**
 * Implementation of hook_views_pre_render(&$view).
 */
function wn_map_views_pre_render(&$view) {
  if (($view->name == 'donation_opportunities') && ($view->current_display == 'page_1')) {
    if (user_access('Allow Reordering')) {
          $view->attachment_before .= '<div class="draggable"><a href="/donate/draggable">[Sort donations]</a></div>';
    }
  } elseif (($view->name == 'take_action') && ($view->current_display == 'page_1')) {
      if (user_access('Allow Reordering')) {
            $view->attachment_before .= '<div class="draggable"><a href="/take_action/draggable">[Sort campaigns]</a></div>';
      }
    }
}