<?php

/**
 * Implementation of hook_menu().
 */
function watershednow_helper_menu() {
  $items = array();

  $items['admin/dashboard'] = array(
    'title' => 'Watershed Now Dashboard',
    'page callback' => 'watershednow_helper_dashboard',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'watershednow_helper.admin.inc',
    'weight' => -20,
  );

  return $items;
}

/**
 * Implementation of hook_form_alter().
 *
 * Borrowing heavily from Development Seed.
 */
function watershednow_helper_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'system_site_information_settings':
    // Allow for custom page title on site front page
      $form['site_name']['#title'] = 'Website Name';
      $form['site_name']['#description'] = 'The name of this website - Generally recommended to be your organization\'s name.';
      $form['site_slogan']['#access'] = FALSE;
      $form['site_mission']['#access'] = FALSE;
      $form['site_footer']['#access'] = FALSE;
      $form['anonymous']['#access'] = FALSE;
      break;
    case 'system_themes_form':
    // Hide cruddy themes that we don't want folks to use, as well as admin themes that are fixed.
      $hidden_themes = array('bluemarine', 'chameleon', 'garland', 'minnelli', 'marvin', 'pushbutton', 'cube', 'rubik', 'tao');
      foreach ($hidden_themes as $theme) {
        unset($form[$theme]);
        unset($form['status']['#options'][$theme]);
        unset($form['theme_default']['#options'][$theme]);
      }
      break;
  }
}